### ISSUE TITLE
Add new page .... item for blogs

### ISSUE THREAD

**Issue by rsmarples** [getgrav/grav#1356]
When adding a new page under a blog, the default template is default.
Surely it should be item so things like breadcrumbs and comments work.

**Comment by rhukster** [comment]
Pretty sure this is fixed in RC release. Can you switch to testing gpm in system config and update?

**Comment by rsmarples** [comment]
I updated to grav and admin panel to testing .... issue persists.
Add page - no parent folder selected, template is default. Select blog to be parent, template remains default.
Add a another page, parent folder is still blog and template is still default.

**Comment by rsmarples** [comment]
Grav v1.2.0-rc.1 - Admin v1.3.0-rc.1

**Comment by rhukster** [comment]
Can you check your parent page has a "Default Child Type" set?

<img width="1196" alt="2017-03-20 at 11 06 am" src="https://cloud.githubusercontent.com/assets/1084697/24111824/5551b4c4-0d5d-11e7-866d-35eb5def52a6.png">

**Comment by rsmarples** [comment]
I just updated Grav and plugins to the latest RC and it's now fixed for Blog items :)
