### ISSUE TITLE
'/admin/preview' of '/' doesn't work

### ISSUE THREAD

**Issue by Verequies** [getgrav/grav#2426]
Hey Guys,

Just installed Grav and having a look around. Looks great so far!

Found an issue with the page preview, which I sure would be a simple fix. 
If you preview the root '/' so '/admin/preview' nothing appears, however if you change the URL to '/admin/preview/home' it works fine.

**Comment by rhukster** [comment]
Already fixed in Admin 1.9 RC.

**Comment by Verequies** [comment]
I am running Admin 1.9 RC4, and this is still an issue. I even just cloned admin git branch 1.9 and tested.

**Comment by rhukster** [comment]
What does your user/config/system.yaml look like?

**Comment by Verequies** [comment]
This is my current system.yaml ( added .txt extension so that I could upload )

[system.yaml.txt](https://github.com/getgrav/grav/files/3052097/system.yaml.txt)

**Comment by Verequies** [comment]
Any ideas? I've updated to the 1.6.1 stable and still having the issue.

**Comment by rhukster** [comment]
I'm still aware of this, but higher priority was to get Grav 1.6 released

**Comment by rhukster** [comment]
Sorted it!

**Comment by rhukster** [comment]
https://github.com/getgrav/grav-plugin-admin/commit/adc7ba3808d31b8b9bcfd3aac0d7cd7d18864052

**Comment by Verequies** [comment]
Awesome, thanks! Just tested the fix and it definitely works :)
