### ISSUE TITLE
Flex users - problem with authorization

### ISSUE THREAD

**Issue by lufog** [getgrav/grav#2444]
If you register a new flex user, and try to log in. You get an error "Login failed...".
This happens both when the user is registered from the site, and when the first user is created from the admin plugin.

```yaml
# system.yaml
...
accounts:
  type: flex
  storage: file
...
```

Access rights are correct:
```yaml
# {profile_hash}.yaml
...
access:
  site:
    login: 'true'
...
```
or
```yaml
# {profile_hash}.yaml
...
groups:
  - user
...
```

```yaml
# groups.yaml
...
user:
  groupname: user
  readableName: User
  access:
    site:
      login: true
...
```
If you regenerate an account index file, old accounts also stop logging in.

**Comment by lufog** [comment]
Not sure, but maybe this information will be useful.
Exceptions:
Flex: accounts index cache not enabled
E:\Development\Web\site\system\src\Grav\Framework\Flex\FlexDirectory.php#318
Flex: accounts object cache not enabled
E:\Development\Web\site\system\src\Grav\Framework\Flex\FlexDirectory.php#318

**Comment by mahagr** [comment]
Those errors are there just for debugging purposes. Flex users is still an experimental feature and may have some issues depending on the configuration.

**Comment by mahagr** [comment]
@lufog This one should be fixed in CI build.

**Comment by lufog** [comment]
The problem is not resolved. When flex is enabled, a new registered user cannot log in. 
At the same time, if you rename the account file from ```6fe43d2989668fc43d1cf363848c655e.yaml``` to ```username.yaml```, authorization will work.

versions:
grav:   git-branch-1.7   (02.09.19)
admin git-branch-1.10 (02.09.19)

system.yaml:
```
...
accounts:
  type: flex
  storage: file
...
```

**Comment by lufog** [comment]
@mahagr, please read the previous comment.

**Comment by mahagr** [comment]
@lufog Should be fixed now for the next version. Thanks for reporting this issue; Flex users will be more of a thing in Grav 1.7.
