### ISSUE TITLE
Status: Googlebot blocked by robots.txt

### ISSUE THREAD

**Issue by the-s-a-m** [getgrav/grav#3067]
The following resources can not be loaded by googlebot because they are blocked by default by robots.txt

/system/assets/jquery/jquery-2.x.min.js
/user/plugins/form/assets/form-styles.css
/user/plugins/login/css/login.css

Thank you for fixing this error in the default configuration

**Comment by NicoHood** [comment]
The current robots is:
```
User-agent: *
Disallow: /backup/
Disallow: /bin/
Disallow: /cache/
Disallow: /grav/
Disallow: /logs/
Disallow: /system/
Disallow: /vendor/
Disallow: /user/
Allow: /user/pages/
Allow: /user/themes/
Allow: /user/images/
Allow: /
```

Maybe it would make sense to add `Allow: /user/plugins/` to the list?
Why is it important to load the listed resources? Does google even care about javascript and css?

**Comment by the-s-a-m** [comment]
Google told me that the access is not possible therefore I changed it to

`User-agent: *
Allow: /user/pages/
Allow: /user/themes/
Allow: /user/images/
Allow: /user/plugins/
Allow: /system/assets/jquery/jquery-2.x.min.js
Disallow: /backup/
Disallow: /bin/
Disallow: /cache/
Disallow: /grav/
Disallow: /logs/
Disallow: /system/
Disallow: /vendor/
Disallow: /user/
Allow: /
`

and now it is working

**Comment by rhukster** [comment]
Fixed by https://github.com/getgrav/grav/commit/bc22c8d2b1efad6f28608aa937e9dd0485eac6d7

**Comment by NicoHood** [comment]
It seems that the issue is not fixed for the builtin jquery:
`/system/assets/jquery/jquery-2.x.min.js`

The reason why this happens is unclear to me. It might be that `Allow: *.js$` does not include `script.min.js` syntax (at least from my observations, as other `.js` scripts work. Searching around in google i found [this post](http://www.thesempost.com/how-to-unblock-all-css-javascript-for-googlebot-using-robots-txt/) that suggests the following:

```
User-Agent: Googlebot
Allow: .css
Allow: .js
```

This also allows query parameters that are often used for cache busting: `https://example.com/deep/style.css?something=1`. And yes, `User-Agent: Googlebot` is important to use here! Another option is to explicitly allow the jquery path.

**Comment by NicoHood** [comment]
From my google search console I also want to note, that fonts (woff, ttf, woff2) and images (jgp, png) inside the plugin/theme folder cannot be crawled. I guess a more general robots.txt solution would make sense.

**Comment by rhukster** [comment]
That's pretty odd, as the allow's are coming after the disallows.  But if it works in your testing, them i'm good with it.  Thanks.

**Comment by NicoHood** [comment]
I've read, that the length of the rule matters for the googlebot. That makes totally sense why `Allow: /system/*.js$` is required.

I also found out, why the other resources we unable to load: Google stops loading resources, if there are too many. It seems like a long standing crawling bug, I could work around this by enabling the assets manager. See https://support.google.com/webmasters/thread/4425254?hl=en

**Comment by rhukster** [comment]
I had aready commited this to 1.7 branch:  https://github.com/getgrav/grav/commit/14df5a6d5fcff55ae0eabd38d2fdddbbe49fd0b9
