### ISSUE TITLE
Admin Panel : Add plugin error, GPM index : error 

### ISSUE THREAD

**Issue by Ribero** [getgrav/grav#3158]
I'm using Grav v1.7.0 - Admin v1.10.0

When trying to add a Plugin (by pressing the add button on top right) instead of having the list of available plugin I get this error:

<img width="2048" alt="image" src="https://user-images.githubusercontent.com/2266264/105107661-d80ac980-5ab8-11eb-8ca4-d001f68eb0c4.png">

Environment & details: 
[Crikey! There was an error.html.zip](https://github.com/getgrav/grav/files/5839312/Crikey.There.was.an.error.html.zip)

when trying to list the plugins using `php ./bin/gpm index`

I get this error:

```
GPM Releases Configuration: Stable
PLUGINS [ 347 ]
Fatal error: Uncaught TypeError: Argument 1 passed to Grav\Console\Gpm\IndexCommand::sort() must be an instance of Grav\Common\GPM\Remote\Packages, instance of Grav\Common\GPM\Remote\Plugins
 given, called in /var/www/html/system/src/Grav/Console/Gpm/IndexCommand.php on line 125 and defined in /var/www/html/system/src/Grav/Console/Gpm/IndexCommand.php:255
Stack trace:
#0 /var/www/html/system/src/Grav/Console/Gpm/IndexCommand.php(125): Grav\Console\Gpm\IndexCommand->sort(Object(Grav\Common\GPM\Remote\Plugins))
#1 /var/www/html/system/src/Grav/Console/GpmCommand.php(41): Grav\Console\Gpm\IndexCommand->serve()
#2 /var/www/html/vendor/symfony/console/Command/Command.php(255): Grav\Console\GpmCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\
ConsoleOutput))
#3 /var/www/html/vendor/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Cons
ole\Output\ConsoleOutput))
 in /var/www/html/system/src/Grav/Console/Gpm/IndexCommand.php on line 255
```

Log file:
[log.txt](https://github.com/getgrav/grav/files/5839262/log.txt)

**Comment by rhukster** [comment]
Hmm. I can't replicate that. It almost appears like you have things out of date.  Did you install Grav + Admin via GPM update? if you upgraded manually or by Git, have you run `bin/grav composer install --no-dev` to get the latest libraries.

**Comment by rhukster** [comment]
Btw, have you also tried forcing a GPM update with `bin/grav index -f` ?

**Comment by Ribero** [comment]
> Btw, have you also tried forcing a GPM update with `bin/grav index -f` ?

Yes same result

**Comment by Ribero** [comment]
> Hmm. I can't replicate that. It almost appears like you have things out of date. Did you install Grav + Admin via GPM update? if you upgraded manually or by Git, have you run `bin/grav composer install --no-dev` to get the latest libraries.

I use the official docker image, then upgraded to 1.7 using the Admin Panel web GUI. I installed Learn2 Git theme and the plugin to manage pages revisions. 

Is there a way to activate more logs ?

**Comment by mahagr** [comment]
Which version of PHP you're in? As I cannot reproduce this either in 7.3.26, 7.4.14 or 8.0.1. That said I kind of get where the issue comes from, but I wonder how to reproduce it..

**Comment by mahagr** [comment]
Nevermind, I found a way to reproduce this issue. :) Fixing it now.

**Comment by mahagr** [comment]
@Ribero Fixed CLI first. You can see my fix from above ^.

**Comment by mahagr** [comment]
The admin issue seems to come from an installed Presentation plugin, try disabling it first.

**Comment by mahagr** [comment]
It looks like path `user/plugins/presentation/node_modules/reveal.js/css/theme` does not exist in your installation, can you check it out? Maybe try to re-install the plugin after disabling it.

**Comment by mahagr** [comment]
Note: CLI issue was fixed, admin issue isn't in Grav or Admin.

**Comment by Ribero** [comment]
> It looks like path `user/plugins/presentation/node_modules/reveal.js/css/theme` does not exist in your installation, can you check it out? Maybe try to re-install the plugin after disabling it.

I uninstalled all plugins, all themes (reverting to Quark) but I still face the same behavior

Cannot add any new plugin using Admin Pannel Gui
Cannot use gpm index -f without a crash

**Comment by Ribero** [comment]
Ok here is an update:

I manually deleted the folder user/plugins/presentation that was still present even if not listed as an installed plugin

Immediate effect is that the Admin Panel GUI is working again as expected !

but 

gpm index -f still crashes.

**Comment by mahagr** [comment]
GPM command has been fixed in a commit above. You can test it if you want by copying
f724367e866ef5b/system/src/Grav/Console/Gpm/IndexCommand.php into `system/src/Grav/Console/Gpm/IndexCommand.php`.

**Comment by Ribero** [comment]
Tested it works. Thanks !

**Comment by OleVik** [comment]
The Presentation-plugin most definitely ships with the [`user/plugins/presentation/node_modules/reveal.js/css/theme`](https://github.com/OleVik/grav-plugin-presentation/tree/v4.0.1/node_modules/reveal.js/css/theme)-folder, and it is non-empty. Unless your system prevented the normal installation of the plugin, the blueprints should have no problem rendering the fields, and should [fall back to `None` being the only option if it fails](https://github.com/OleVik/grav-plugin-presentation/blob/v4.0.1/presentation.php#L475-L488) to list the themes.
