### ISSUE TITLE
Pages search is performed only by folder name

### ISSUE THREAD

**Issue by Karmalakas** [getgrav/grav#3316]
Am I assuming correctly, that pages search in Admin should be on [these four fields](https://github.com/getgrav/grav/blob/develop/system/blueprints/flex/pages.yaml#L185)?

I've tried it seems everything (even editing the system ... pages.yaml and completely emptying cache directory and then saving a page), but it searches only by `name` (it's folder I guess). Wanted to help [here on Discourse](https://discourse.getgrav.org/t/search-pages-by-slug-or-title-in-admin-grav-version-1-7/16942), but it seems there's a bug.

Other custom flex-objects I have work perfectly fine with fields defined in this config path.

Did some debugging and here's what I found:
1. Children pages return `null` properties
`$property` here is `title`, but `$this` _PageObject_ does not contain it and returns `null` and therefore page does not match the search phrase `tipo`
![image](https://user-images.githubusercontent.com/3602819/115062339-ec613580-9ef2-11eb-9f03-9e8f1c98ece0.png)

1. Even though I definitely have such page. This _Tipo_ page is a _typography_ folder page
![image](https://user-images.githubusercontent.com/3602819/115062406-fb47e800-9ef2-11eb-94b1-f7b657503193.png)

1. Here's a full view when `PageObject::getNestedProperty()` returns `null`
![image](https://user-images.githubusercontent.com/3602819/115062582-2cc0b380-9ef3-11eb-8668-625a18f29ab1.png)
    1. ArrayProperty doesn't check in header
![image](https://user-images.githubusercontent.com/3602819/115062614-364a1b80-9ef3-11eb-8c87-10f7aad1582b.png)
    1. And ObjectProperty checks defined properties, which doesn't look like a place to be searched 
![image](https://user-images.githubusercontent.com/3602819/115062631-3c3ffc80-9ef3-11eb-8cb1-f9d51dabb533.png)

Beyond that point I can only guess how it's supposed to be, hence the issue :)

**Comment by masetto** [comment]
Hi @mahagr, are you sure that issue is fixed? Because if I search by title I have not expected results.

**Comment by mahagr** [comment]
It works for me, just searched for a title.

**Comment by masetto** [comment]
Are you sure that the title is different from folder name?

**Comment by Karmalakas** [comment]
I completely forgot to test this. Will try probably after work

**Comment by mahagr** [comment]
Yeah, they had no common letters in them.

**Comment by Karmalakas** [comment]
For me now it searches by Page Title and Menu Title, but does not by folder name nor by slug. Is it supposed to be like this?

**Comment by masetto** [comment]
Hi, sorry, but for me it does not work and I don't understand why... This is my page frontmatter:
```
title: 'Senza titolo'
taxonomy:
    category:
        - Rinascita
    tag:
        - artwork
        - winner
        - biennale
template: artwork
firstname: Li
lastname: Yichen
```
The folder name is `li-yichen`. I'm using `Grav v1.7.17 - Admin v1.10.17` on Linux.
In admin pages, if I search `titolo` I have no results.

**Comment by Karmalakas** [comment]
By any chance you have a multi-language site and search in a wrong language, @masetto? Just guessing

**Comment by mahagr** [comment]
I removed name (template has it's own filter) and added slug to search fields.

**Comment by Karmalakas** [comment]
> I removed name (template has it's own filter) and added slug to search fields.
> 
> Can you try (see the commit) if it now behaves how you expect it to?

Now it searches exceptionally only by folder. Neither Menu/Page title nor slug works

**Comment by mahagr** [comment]
@Karmalakas I cannot reproduce your issue. The search uses both title and slug, I tested that by using a different language.

**Comment by Karmalakas** [comment]
I tried on two languages 😕 Will try again later on fresh install 🤔

**Comment by mahagr** [comment]
So maybe this issue is multilanguage-related...

**Comment by mahagr** [comment]
I can confirm that the issue is present with multilanguage, when you select another language than the default one.

**Comment by Karmalakas** [comment]
I tried both default and not 🤔 
I see you added the label _Fixed_, but is it really? Or there should be another issue created for multi-language pages search?

(I'll still try on fresh install)

**Comment by mahagr** [comment]
No, I removed the fixed tag :)

Actually there were two issues: 
- the slug was not in the search field list
- when using multi-language, search is performed before looking at the translated items

The first one has been fixed, but the second one has not.

**Comment by Karmalakas** [comment]
> No, I removed the fixed tag :)

My bad 🤦‍♂️ 

---

Thanks for the clarification :)

**Comment by masetto** [comment]
Hi,
sorry, but the search still doesn't work for slug and title with multiple languages, not even for the default language.

**Comment by phmg701** [comment]
Hello, I can confirm search is only performed by original folder name. No slug search, no tile search.
It would be great to have wider search options at least for the selected language.
Thank you!

**Comment by mahagr** [comment]
Should now be fixed. Search and filtering in general now matches the displayed items. The fix will be released early next week.

**Comment by phmg701** [comment]
Confirmed working by searching both slug or title in 2nd language and not returning result for the main language (English) as expected. Fresh local 1.7.31 install just updated to 1.7.32. Thanks!

**Comment by Karmalakas** [comment]
Finally got to it 🙂  Sorry for the delay and keeping issue open.
Just tested and it seems to be working as expected. Thank you 🙂
