### ISSUE TITLE
Data validation fails for some numbers

### ISSUE THREAD

**Issue by TheoAcker12** [getgrav/grav#3585]
This is related to issue #3433.

To replicate the error: Create a number field with validate.step of .0000001 and validate.min -90. Try inputting value 81.96 on the admin panel blueprint.

Expectation: The blueprint saves.

Result: The blueprint fails to save, indicating invalid input in that field.

A couple of notes:

- Changing the step to .000001, removing the min, or changing the input value to 81.9 or 81.9692 (as a few examples) all provide the expected result. Changing the step .00001, however, still fails validation. This is consistent with issues with the PHP fmod function.
- The fmod function used to be used in Grav/Common/Data/Validation.php in the typeNumber function (and did, in fact, cause the exact problems expected). It is no longer used in that function, however, so I think the error must be introduced elsewhere.

**Comment by mahagr** [comment]
Yes, I removed fmod() call because it had rounding issues. I think the issue comes from how floating points work, they are never accurate due to how they are being saved. There's no other code anywhere, I bet the precision error comes from div.

**Comment by TheoAcker12** [comment]
That makes sense. What would be the best way to deal with the issue? Is there anything I can do short of changing the input to a text field?

**Comment by mahagr** [comment]
Not sure. I already fixed this as this was supposed to be the better working solution (and it was).

**Comment by TheoAcker12** [comment]
I can't think of a way to deal with PHP's issues in this regard. Maybe there isn't one, or maybe it just requires a very creative solution, but as long as we don't have a solution this probably shouldn't be a thing at all. Can step be removed from the validation function, or at the very least can there be an option to set in the blueprint that will ignore step? Right now if I don't include a step value it just defaults to 1, so I'm forced to include the step value.

Frankly, I would just say ignore step values of .001 or lower: i.e. `if (isset($params['step']) && ($params['step'] > .001)`.  Since the validation won't be accurate anyways, it would be better to err on the side of allowing the input than not allowing it.

**Comment by sridharkalaibala** [comment]
I reproduced the reported numeric-step case on current develop d581c327c: 81.96 with min -90 and step 0.0000001 still fails, so I am not treating that precision issue as resolved.

There is also a smaller problem with opting out: `step: any` reaches the number-field HTML correctly, but core casts it to zero and raises DivisionByZeroError. I submitted #4308 to handle that explicit keyword while retaining numeric/min/max validation. Its regression tests fail before and pass after the fix. This provides an explicit no-grid option; it does not change the precision behavior of numeric steps or close this issue.

**Comment by sridharkalaibala** [comment]
**Update after extended testing: the candidate below is not ready for a patch.** A 96-case large-magnitude set produced 15 disagreements with Chromium. For example, min `1000000000`, step `0.000001`, value `1000000000.0000005` is between steps: Chromium and current core reject it, but the proposed tolerance accepts it. Scaling by the absolute base lets the tolerance exceed the distance to a neighboring step. Some still smaller decimal differences also disappear on conversion to binary floats, so exact-decimal expectations alone are not a sufficient oracle at that scale. I am not proposing this formula for production without a more robust strategy; #4308 remains independent and unchanged.
I also investigated the numeric-step failure separately from #4308. For the reported values, `(81.96 - -90) / 0.0000001` lands slightly above an integer; rounding the quotient to ten decimal places does not remove that error.

I tried an isolated candidate that reconstructs the nearest allowed value and compares in value units:

```php
$offset = round(($value - $min) / $step) * $step;
$closest = $min + $offset;
$tolerance = 4 * PHP_FLOAT_EPSILON * max(abs($value), abs($min), abs($offset));
$matches = abs($value - $closest) <= $tolerance;
```

The experiment keeps the existing number/min/max checks. On a deterministic 301-case set built with exact decimal arithmetic (five base values, five decimal steps, six grid positions, exact-grid and half-step inputs, plus this issue's example), current core rejects 39 valid inputs; this candidate matches all expected results. Chromium's number-input validation agrees on all 301 cases too.

This is preliminary evidence, not a general floating-point proof. Values near representation limits, extreme magnitudes, invalid step configuration and the appropriate tolerance factor need further review. Would a separate PR using this value-space approach be welcome, or would you prefer another numerical strategy? No numeric-step production change is included in #4308.

**Comment by rhukster** [comment]
Good instinct withdrawing the tolerance approach — you were right about why it fails. Scaling by the absolute base lets the tolerance exceed the distance to the neighbouring step, and no amount of tuning the factor fixes that, because the problem isn't the factor, it's that the comparison is happening in binary floats at all.

The way out is to not use floats. `typeNumber()` receives the decimal text — from the blueprint for min and step, from the form for the value — and casts it to float on the first line, which is where the precision goes. Scaling all three to a common power of ten turns "is this on the grid" into integer arithmetic, where it has an exact answer:

```
81.96 with min -90, step 0.0000001
-> value 819600000, min -900000000, step 1, at scale 7
-> (819600000 - -900000000) % 1 == 0  ->  valid
```

Native integers cover every range and step a blueprint realistically uses; bcmath takes anything past 18 digits where it's installed, and the old float comparison stays as a fallback for input that isn't decimal text at all.

I swept it: 1260 generated cases across seven minimums, nine steps and ten grid positions, each tested on-grid and at a half-step offset, with and without bcmath. Zero disagreements. Current core rejects 96 of those same valid inputs, including your 81.96 case and every `1000000000.x` case. Full core suite stays green.

So this is fixed rather than mitigated, and there's no tolerance constant to argue about. Your #4308 went in alongside it — `any` is still the right explicit opt-out and the case-insensitivity catch was a good one. I extended it to the other ways that line could divide by zero (`0`, `'0'`, `''`, `false`, a non-numeric step, and `typeRange`), plus the same fault in `typeArray()` that `typeSelect()` runs through.

Fixed on develop, shipping in **2.1.6**. Thanks for the careful work on this, and particularly for testing your own candidate hard enough to reject it — that saved a bad patch.
