### ISSUE TITLE
[add-resource] New Plugin: StaticMath

### ISSUE THREAD

**Issue by 9p4** [getgrav/grav#3737]
I would like to add my new plugin to the Grav Repository.

This plugin converts LaTeX to static math (with some CSS) using server-side [KaTeX](https://katex.org/).

Here are the project details: https://github.com/9p4/grav-plugin-staticmath

I am mirroring the repository from Sourcehut to Github.

Supersedes https://github.com/getgrav/grav/issues/3699

**Comment by rhukster** [comment]
This will not be added until you create a release... Please follow the guidelines: https://learn.getgrav.org/17/advanced/grav-development#theme-plugin-release-process

Cheers!

**Comment by 9p4** [comment]
Sorry about that, should be fixed now.

**Comment by rhukster** [comment]
hmm.. still not seeing any 'releases': https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository

**Comment by 9p4** [comment]
For some reason it's not appearing in the Github page, but the releases are added: https://github.com/9p4/grav-plugin-staticmath/releases
