### ISSUE TITLE
Error page after logging into admin plugin.

### ISSUE THREAD

**Issue by mikegcox** [getgrav/grav#488]
Grav site has been working perfectly on my localhost and usually works well on my host (Wirenine).  A few times now upon logging into the admin panel I would get an error that looked like this:
```
Whoops\Exception\ErrorException thrown with message "Call to a member function content() on null"

Stacktrace:
#0  in /home/ffcmsbiz/public_html/vintagemoto.ca/system/src/Grav/Common/Twig/Twig.php:300

 Open: /home/ffcmsbiz/public_html/vintagemoto.ca/system/src/Grav/Common/Twig/Twig.php

         */
        public function processSite($format = null)
        {
            // set the page now its been processed
            $this->grav->fireEvent('onTwigSiteVariables');
            $pages = $this->grav['pages'];
            $page = $this->grav['page'];
            $content = $page->content();
            $config = $this->grav['config'];
```
I have several sites on Wirenine and two of them had this error, three of them were fine.  After much trial and error I finally got logged in by deleting my user/admin.yaml file and creating a new user from command line: `bin/plugin login new-user`. After that I was able to get logged in and everything is just fine.  I am not sure why this happened, I did notice that the create user process has been updated adding an enabled or disabled switch.  This has happened intermittently on two different sites for a week or so now.

**Comment by mikegcox** [comment]
This could be an issue of improper handling of username and password.  I just tried to log in with improper credentials on this site and I get the same Crikey error. If I try to log in with the wrong credentials on my localhost site I get a proper message.  On the same site hosted on wirenine, if I type in the wrong credentials, I get the Crikey error above.  If you like, give it a try.  Go to www.vintagemoto.ca and try to log in with the wrong creds.

**Comment by rhukster** [comment]
I think this is a combination of things that might be already fixed.  First, there's a problem with the routing, and Grav admin plugin had a bug that it would throw this error if the route didn't exist.  This has been fixed for the next release.  However, the page should exist, and that might be related to the nonces which have also been updated.  I think we should postpone this to the next round of releases and see if that addresses it.

**Comment by mikegcox** [comment]
Okay, I will test again after the next update and report back

**Comment by mikegcox** [comment]
I successfully upgraded the above site and I still have the issue of bad routing upon login.  This only happens on my remote host, localhost works perfectly.

**Comment by rhukster** [comment]
Ok, then there is something wrong with your remote setup.  Either there are files missing, permissions issues, or bad configuration of either Grav or your server environment.  

I'm not really sure where you should start, but if it were me, i would back up my remote state.  Then zip up my local, copy over to remove, and extract it.  See if that works.

**Comment by mikegcox** [comment]
Okay, thanks, I will keep digging and let you know.  I have zipped my entire production site, moved it over and unzipped twice now chasing this one so it is definitely something strange with my host.

**Comment by rhukster** [comment]
Closing for now as it seems to be host related somehow.
