### ISSUE TITLE
[add-resource] New Skeleton

### ISSUE THREAD

**Issue by MATsxm** [getgrav/grav#595]
I would like to add my new Skeleton "Prickly Pear" to the Grav repository.
Here are the project details: **https://github.com/CaribThemes/grav-skeleton-pricklypear**

It seems I missed something but I can not find where.
Thanks for the help.

FYI, I also updated (minor fix) the "standalone" to a v1.0.2: 
https://github.com/CaribThemes/grav-theme-pricklypear

Thanks

**Comment by rhukster** [comment]
You need to 'build' your skeleton package and upload that into the release for the skeleton.  Check any other skeleton for an example:

https://github.com/getgrav/grav-skeleton-blog-site/releases

The zip is a package that contains Grav + theme + content + plugins + config etc

**Comment by giansi** [comment]
@MATsxm here is an article that could help you http://diblas.net/blog/how-to-build-a-grav-skeleton

**Comment by MATsxm** [comment]
Thanks a lot @giansi for your great article but unfortunately, I've never been a Master of CLI (I know that sounds stupid :wink:  ) so I had to find other solutions but thanks for the help and the step by step.

@rhukster lets see if this version passes the test?
https://github.com/CaribThemes/grav-skeleton-pricklypear

**Comment by rhukster** [comment]
It's still not working, i'm getting a failed on getRelease.. The only thing I can think of i you have a capital `V` for version, can you try renaming the file with a lowercase `v` and replacing the file in the release?

**Comment by MATsxm** [comment]
hmm
Done
Thanks @rhukster for the time you spend on it

**Comment by rhukster** [comment]
Damn still not working.  I'm going to have to talk to @w00fz about this on monday.

**Comment by MATsxm** [comment]
:+1: thanks

**Comment by w00fz** [comment]
Fixed :confetti_ball:

**Comment by MATsxm** [comment]
Thanks Guys! :bow: 
you all rock!

**Comment by w00fz** [comment]
Nothing wrong on your end, there was a typo in our repository yaml. Technically the repo generator was right, it couldn't find a Release, but only because it was looking at a repository that wasn't yours :smile:

**Comment by rhukster** [comment]
doh my fault! thanks for sorting @w00fz
