### ISSUE TITLE
[add-resource] New Plugin

### ISSUE THREAD

**Issue by ellioseven** [getgrav/grav#626]
I would like to add my new plugin to the Grav Repository. Here are the project details:

https://github.com/ellioseven/grav-plugin-view

**Comment by rhukster** [comment]
Tried adding your plugin to GPM, and it failed on the blueprints.  There are many fields you are missing. Please use one of the worknig blueprints as a guide or check the docs: http://learn.getgrav.org/advanced/blueprints

**Comment by rhukster** [comment]
@ellioseven please read above.

**Comment by ellioseven** [comment]
Thanks for the reminder! I have fixed up the blueprints, hopefully it's all good

**Comment by rhukster** [comment]
It's still failing on the blueprints.  Are you sure the 'released' version has these blueprint fixes?

**Comment by ellioseven** [comment]
That was the problem, I updated the release :)

**Comment by rhukster** [comment]
Yup you got it.. shows in GPM now.. Cheers!
